admin:
  username: admin
  password: 21232f297a57a5a743894a0e4a801fc3
server:
  port: 3000
  host: 0.0.0.0
  jwt_secret: vue-file-manager-secret-key-2024
language: en-US
storage_root: ./uploads
upload_limit: 100
max_concurrent_uploads: 3
resumable_upload_cache_minutes: 120
ip_list_mode: blacklist
site:
  icp_beian: ''
  police_beian: ''
database:
  type: sqlite
  sqlite:
    path: ./data/filemanager.db
  mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: ''
    database: vue_file_manager
    ssl: false
  postgres:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: ''
    database: vue_file_manager
    ssl: false
storage_pools:
  - name: 本地存储
    type: local
    default: true
    config:
      localPath: ./uploads
smtp:
  enabled: false
  host: smtp.example.com
  port: 465
  secure: true
  user: noreply@example.com
  pass: your-password
  from: VueFileManager <noreply@example.com>
plugins:
  enabled: true
  dir: ./plugins
